import os
import re

filepath = "c:/Users/Leonardo/001/TXT/GMRTI/GMRTI_008.md"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Preamble Update
content = content.replace("GMRTI - General Method for Refinement and Transmission of Ideas\n### A Living Framework Document * Eighth Iteration (v0.7)", "GMRTI — General Method for Refinement and Transmission of Ideas\n### A Living Framework Document · Ninth Iteration (v0.8)")
content = content.replace("GMRTI — General Method for Refinement and Transmission of Ideas\n### A Living Framework Document · Eighth Iteration (v0.7)", "GMRTI — General Method for Refinement and Transmission of Ideas\n### A Living Framework Document · Ninth Iteration (v0.8)")
content = content.replace("This eighth formal articulation of the General Method", "This ninth formal articulation of the General Method")
content = content.replace("takes v0.6 as its base while executing three repairs", "takes v0.7 as its base while executing seven structural repairs to resolve identified logical dissonances. These include: aligning Redundancy-Masking with the metaagnostic epistemic limits, splitting Generative Reconstruction into a two-phase Mirror/Generative process, redefining Severe Edge Deficit to avoid Node Substantialism, introducing Operational Parking, and restricting Syntactic Edge-Forcing to structural layers.")

# 2. Severe Edge Deficit -> Anchor-Only Subgraph
content = content.replace("**Severe Edge Deficit** — The transmitting covenant attempts to reference an edge-cluster for which the receiving covenant has an absolute topological void. The receiver cannot even register what is missing; absence of a cluster is not self-announcing. This is the deepest and most dangerous divergence type, and the one most requiring Polyphonic Encoding as preventive strategy.", "**Anchor-Only Subgraph (formerly Severe Edge Deficit)** — The transmitting covenant attempts to reference an edge-cluster for which the receiving covenant has a shared surface label (a word or artifact) but possesses zero internal relational depth attached to it. The receiver is not pointing at a void, but at a hollow shell. This is the deepest and most dangerous divergence type, requiring Polyphonic Encoding to construct internal topology behind the shared label.")
content = content.replace("Severe Edge Deficits", "Anchor-Only Subgraphs")
content = content.replace("Severe Edge Deficit", "Anchor-Only Subgraph")

# 3. Redundancy-Masking (Fix Catch-22)
old_rm = """**2f.5iv** The practical prescription: after a Polyphonically Encoded transmission is received successfully, the parties should perform at minimum one targeted probe of the transmission via a *stripped* path — a single-route version — to test whether the successful reception was robust or merely redundancy-sustained. `[PROVISIONAL]`"""
new_rm = """**2f.5iv** The Metaagnostic Acceptance of Redundancy-Masking: Because the goal of redundancy is not to ensure unequivocal verification but to maximize the probability of reconstruction, attempting to test for Redundancy-Masking via a 'stripped path' violates the framework's own epistemic limits. We accept Redundancy-Masking not as a solvable failure mode, but as an irreducible condition of robust transmission. The comosí generated by redundancy is sufficient until downstream action breaks it. `[STABLE]`"""
content = content.replace(old_rm, new_rm)

# Replace hyphen variations just in case
old_rm2 = """**2f.5iv** The practical prescription: after a Polyphonically Encoded transmission is received successfully, the parties should perform at minimum one targeted probe of the transmission via a *stripped* path - a single-route version - to test whether the successful reception was robust or merely redundancy-sustained. `[PROVISIONAL]`"""
content = content.replace(old_rm2, new_rm)

# 4. Stage 1: Remove upfront edge-typing
old_stage1_v = """- **3b.1v** Indicating, where ambiguity is likely, which relation-type from the Edge Taxonomy is operative — so that Edge-Type Misattribution can be preempted rather than repaired after the fact."""
new_stage1_v = """- **3b.1v** *[Excised in v0.8 to align with JIT-OM principle. Edge-typing is strictly deferred to Stage 3 divergence resolution, maintaining Stage 1 as purely topological.]*"""
content = content.replace(old_stage1_v, new_stage1_v)

old_stage1_v2 = """- **3b.1v** Indicating, where ambiguity is likely, which relation-type from the Edge Taxonomy is operative - so that Edge-Type Misattribution can be preempted rather than repaired after the fact."""
content = content.replace(old_stage1_v2, new_stage1_v)

# 5. Stage 2: Rational Agnosticism vs Generative Reconstruction
old_stage2 = """**3c.1** The receiving party — operating as a Rationally Agnostic Mirror to the degree prescribed by the Domain Risk Coefficient — attempts to build the transmitted concept anew within their own covenant using the transmitting party's declared edge-structure as scaffold. This is the inverse of naive listening, in which a receiver maps incoming signals directly onto their own existing clusters. `[STABLE]`"""
new_stage2 = """**3c.1** Stage 2 is temporally divided to resolve the tension between pure reception and active interpretation:
- **3c.1a (Mirror Mode):** The receiving party operates strictly as a Rationally Agnostic Mirror, suspending interpretive charity to passively map the transmitting party's declared edges exactly as stated, identifying structural gaps.
- **3c.1b (Generative Mode):** Interpretive charity is explicitly re-engaged. The receiver uses their own covenant's topology to build active bridges and scaffolds across the gaps identified during Mirror Mode. `[STABLE]`"""
content = content.replace(old_stage2, new_stage2)

old_stage2_alt = """**3c.1** The receiving party - operating as a Rationally Agnostic Mirror to the degree prescribed by the Domain Risk Coefficient - attempts to build the transmitted concept anew within their own covenant using the transmitting party's declared edge-structure as scaffold. This is the inverse of naive listening, in which a receiver maps incoming signals directly onto their own existing clusters. `[STABLE]`"""
content = content.replace(old_stage2_alt, new_stage2)

# 6. Operational Parking
content = content.replace("Pragmatic Termination", "Operational Parking")
content = content.replace("Pragmatic Action Threshold", "Operational Action Threshold")

# 7. Artifact Anchors and Maintenance Covenants
old_anchor = """**2d.2** Meaning is stabilized across a community via **Artifact Anchors** — written laws, canonical texts, standardized protocols, foundational rituals. These are not themselves semantic covenants. They are external, relatively immutable scaffolds that force individual constituent covenants to continuously realign their Structural Subgraphs to a shared artificial topology. The shared topology is real and functional without requiring that any two members have identical internal covenants."""
new_anchor = """**2d.2** Meaning is stabilized across a community via **Artifact Anchors** — written laws, canonical texts, standardized protocols. However, because artifacts are textual, they are themselves subject to Temporal Drift. Artifact Anchors can only function as immutable scaffolds when paired with an active **Maintenance Covenant** (a prescriptive interpretive body) whose explicit purpose is to continuously negotiate and counteract the artifact's drift using GMRTI principles. The anchor slows drift; the Maintenance Covenant manages the residual. `[STABLE]`"""
content = content.replace(old_anchor, new_anchor)

old_anchor_alt = """**2d.2** Meaning is stabilized across a community via **Artifact Anchors** - written laws, canonical texts, standardized protocols, foundational rituals. These are not themselves semantic covenants. They are external, relatively immutable scaffolds that force individual constituent covenants to continuously realign their Structural Subgraphs to a shared artificial topology. The shared topology is real and functional without requiring that any two members have identical internal covenants."""
content = content.replace(old_anchor_alt, new_anchor)

# 8. Syntactic Edge-Forcing Scope
old_se_scope = """**5a.3 - Concept-Type and Syntactic Edge-Forcing Compatibility** `[PROVISIONAL]`"""
new_se_scope = """**5a.3 - Concept-Type and Syntactic Edge-Forcing Compatibility** `[PROVISIONAL]`\nThe formal layer of the GMRTI explicitly constrains Syntactic Edge-Forcing to Structural and Inferential edges. The framework's General nature requires preserving the high-entropy generativity of Affective and Normative layers for rhetoric and literature, deploying formal edge-forcing strictly for load-bearing topological plumbing."""
content = content.replace(old_se_scope, new_se_scope)

# Update Footer
content = content.replace("End of GMRTI v0.7 - Eighth Iteration", "End of GMRTI v0.8 - Ninth Iteration")
content = content.replace("End of GMRTI v0.7 — Eighth Iteration", "End of GMRTI v0.8 — Ninth Iteration")

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)
print("File successfully rewritten.")
